### ISSUE TITLE
"decide" module should respect the "take decision" doc

### ISSUE THREAD

**Issue by PierreSalaun** [craft-ai/craft-ai-client-js#69]
- should check that all context keys (except output) are given;
- should check the type of the given keys.

-----------

- [x] Add tests in interpreter test (cf. craft-ai/craft-ai-interpreter-test-suite#6)
- [x] Update the js client (cf. #76)
- [x] Update the python client (cf. craft-ai/craft-ai-client-python#56)
